/**
 * CMS Knowledge API client — server-side only.
 *
 * Communicates with the CMS at <CMS_BASE_URL> to fetch and update knowledge
 * documents.  Every request is authenticated with a shared secret sent as a
 * plain Bearer token — matching how the CMS verifies callers:
 *
 *   Authorization: Bearer <CMS_API_SECRET>
 *
 * Endpoints consumed:
 *
 *   GET  <CMS_BASE_URL>/api/chatbot/knowledge?status=<status>&limit=<n>
 *     → KnowledgeDocument[] (each extended with a `download_url` field)
 *
 *   PATCH <CMS_BASE_URL>/api/chatbot/knowledge
 *     Body: { id, status, error_message? }
 *     → KnowledgeDocument (the updated row)
 *
 * NEVER import this module from client-side code.
 */

// ── Config ────────────────────────────────────────────────────────────────────

function getCmsBaseUrl(): string {
  const url = process.env.CMS_BASE_URL;
  if (!url?.trim()) {
    throw new Error(
      'CMS_BASE_URL environment variable is not set. Set it in .env.local.',
    );
  }
  return url.trim().replace(/\/$/, '');
}

function getCmsApiSecret(): string {
  const secret = process.env.CMS_API_SECRET;
  if (!secret?.trim()) {
    throw new Error(
      'CMS_API_SECRET environment variable is not set. Set it in .env.local.',
    );
  }
  return secret.trim();
}

function authHeader(): { Authorization: string } {
  return { Authorization: `Bearer ${getCmsApiSecret()}` };
}

// ── Types ─────────────────────────────────────────────────────────────────────

export type KnowledgeDocumentStatus =
  | 'pending'
  | 'processing'
  | 'completed'
  | 'failed';

export interface KnowledgeDocument {
  id: string;
  tenant_id: string;
  title: string;
  file_name: string;
  file_type: string;
  file_size: number;
  storage_path: string;
  status: KnowledgeDocumentStatus;
  error_message: string | null;
  uploaded_at: string;
  uploaded_by: string;
  created_at: string;
  updated_at: string;
  /** Signed download URL generated by the CMS (1-hour TTL). Null on error. */
  download_url: string | null;
}

export interface PatchKnowledgeDocumentBody {
  id: string;
  status: 'processing' | 'completed' | 'failed';
  error_message?: string;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Fetch knowledge documents from the CMS.
 *
 * @param status - Filter by processing status (default: `"pending"`).
 * @param limit  - Maximum number of documents to return (default: 50, max: 200).
 */
export async function fetchKnowledgeDocuments(
  status: KnowledgeDocumentStatus = 'pending',
  limit = 50,
): Promise<KnowledgeDocument[]> {
  const url = new URL(`${getCmsBaseUrl()}/api/chatbot/knowledge`);
  url.searchParams.set('status', status);
  url.searchParams.set('limit', String(limit));

  const res = await fetch(url.toString(), {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      ...authHeader(),
    },
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(
      `CMS GET /api/chatbot/knowledge error: HTTP ${res.status}${text ? ` — ${text}` : ''}`,
    );
  }

  return res.json() as Promise<KnowledgeDocument[]>;
}

/**
 * Update the processing status of a knowledge document.
 *
 * @param body - `{ id, status, error_message? }`
 * @returns The updated document row as returned by the CMS.
 */
export async function patchKnowledgeDocument(
  body: PatchKnowledgeDocumentBody,
): Promise<KnowledgeDocument> {
  const res = await fetch(`${getCmsBaseUrl()}/api/chatbot/knowledge`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      ...authHeader(),
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(
      `CMS PATCH /api/chatbot/knowledge error: HTTP ${res.status}${text ? ` — ${text}` : ''}`,
    );
  }

  return res.json() as Promise<KnowledgeDocument>;
}
