/**
 * CMS Knowledge API client — server-side only.
 *
 * Communicates with the CMS to fetch and update knowledge documents.
 * Every outbound request is authenticated with a shared secret:
 *
 *   Authorization: Bearer <CMS_API_SECRET>
 *
 * Secret naming convention:
 *   CMS_API_SECRET      — sent BY this service TO the CMS (outbound).
 *   CHATBOT_API_SECRET  — sent BY the CMS TO this service (inbound, see cms-auth.ts).
 *
 * Endpoints consumed:
 *
 *   GET  <CMS_URL>/api/chatbot/knowledge?status=<status>&limit=<n>
 *     → KnowledgeDocument[]  (each with a `download_url` field)
 *
 *   GET  <CMS_URL>/api/chatbot/knowledge?id=<documentId>
 *     → KnowledgeDocument | null
 *
 *   PATCH <CMS_URL>/api/chatbot/knowledge
 *     Body: { id, status, error_message? }
 *     → KnowledgeDocument (the updated row)
 *
 * NEVER import this module from client-side code.
 */

// ── Config ────────────────────────────────────────────────────────────────────

/**
 * Base URL of the CMS.
 * Reads CMS_URL first (new canonical name), falls back to CMS_BASE_URL
 * for backward-compatibility.
 */
function getCmsBaseUrl(): string {
  const url = (process.env.CMS_URL ?? process.env.CMS_BASE_URL)?.trim();
  if (!url) {
    throw new Error(
      'CMS_URL environment variable is not set. Set it in .env.local.',
    );
  }
  return url.replace(/\/$/, '');
}

/** Secret sent by this service to the CMS for outbound requests. */
function getCmsApiSecret(): string {
  const secret = process.env.CMS_API_SECRET?.trim();
  if (!secret) {
    throw new Error(
      'CMS_API_SECRET environment variable is not set. Set it in .env.local.',
    );
  }
  return secret;
}

function authHeader(): { Authorization: string } {
  return { Authorization: `Bearer ${getCmsApiSecret()}` };
}

// ── Types ─────────────────────────────────────────────────────────────────────

export type KnowledgeDocumentStatus =
  | 'pending'
  | 'processing'
  | 'completed'
  | 'failed';

export interface KnowledgeDocument {
  id: string;
  tenant_id: string;
  title: string;
  file_name: string;
  file_type: string;
  file_size: number;
  storage_path: string;
  status: KnowledgeDocumentStatus;
  error_message: string | null;
  uploaded_at: string;
  uploaded_by: string;
  created_at: string;
  updated_at: string;
  /** Signed download URL generated by the CMS (1-hour TTL). Null on error. */
  download_url: string | null;
}

export interface PatchKnowledgeDocumentBody {
  id: string;
  status: 'processing' | 'completed' | 'failed';
  error_message?: string;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Fetch knowledge documents from the CMS filtered by status.
 *
 * @param status - Filter by processing status (default: `"pending"`).
 * @param limit  - Maximum number of documents to return (default: 50, max: 200).
 */
export async function fetchKnowledgeDocuments(
  status: KnowledgeDocumentStatus = 'pending',
  limit = 50,
): Promise<KnowledgeDocument[]> {
  const url = new URL(`${getCmsBaseUrl()}/api/chatbot/knowledge`);
  url.searchParams.set('status', status);
  url.searchParams.set('limit', String(limit));

  const res = await fetch(url.toString(), {
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...authHeader() },
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(
      `CMS GET /api/chatbot/knowledge error: HTTP ${res.status}${text ? ` — ${text}` : ''}`,
    );
  }

  return res.json() as Promise<KnowledgeDocument[]>;
}

/**
 * Fetch a single knowledge document by its ID.
 *
 * Uses GET /api/chatbot/knowledge?id=<documentId> if the CMS supports it,
 * falling back to a status=pending fetch and local filter.
 *
 * Returns `null` if no document with that ID is found.
 *
 * @param documentId - The CMS document ID to look up.
 */
export async function fetchDocumentById(
  documentId: string,
): Promise<KnowledgeDocument | null> {
  // Try the direct ?id= endpoint first (CMS may or may not support it).
  const url = new URL(`${getCmsBaseUrl()}/api/chatbot/knowledge`);
  url.searchParams.set('id', documentId);

  const res = await fetch(url.toString(), {
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...authHeader() },
  });

  if (res.ok) {
    const body = await res.json() as KnowledgeDocument | KnowledgeDocument[] | null;
    // CMS may return a single doc or an array.
    if (Array.isArray(body)) {
      return body.find((d) => d.id === documentId) ?? null;
    }
    if (body && typeof body === 'object' && 'id' in body) {
      return (body as KnowledgeDocument).id === documentId
        ? (body as KnowledgeDocument)
        : null;
    }
    return null;
  }

  // If the CMS returned 404 or doesn't support ?id=, fall back to a
  // full pending fetch and filter locally.  This ensures compatibility
  // with CMS implementations that only expose the status-filtered endpoint.
  if (res.status === 404 || res.status === 400) {
    const docs = await fetchKnowledgeDocuments('pending', 200);
    return docs.find((d) => d.id === documentId) ?? null;
  }

  const text = await res.text().catch(() => '');
  throw new Error(
    `CMS GET /api/chatbot/knowledge?id=${documentId} error: HTTP ${res.status}${text ? ` — ${text}` : ''}`,
  );
}

/**
 * Update the processing status of a knowledge document.
 *
 * @param body - `{ id, status, error_message? }`
 * @returns The updated document row as returned by the CMS.
 */
export async function patchKnowledgeDocument(
  body: PatchKnowledgeDocumentBody,
): Promise<KnowledgeDocument> {
  const res = await fetch(`${getCmsBaseUrl()}/api/chatbot/knowledge`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...authHeader() },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(
      `CMS PATCH /api/chatbot/knowledge error: HTTP ${res.status}${text ? ` — ${text}` : ''}`,
    );
  }

  return res.json() as Promise<KnowledgeDocument>;
}
